// Menu
export const GET_BURGERS = 'GET_BURGERS';
export const GET_NEW_BURGERS = 'GET_NEW_BURGERS';

export const UPDATE_BURGER_ITEMS_IN_CART = 'UPDATE_BURGER_ITEMS_IN_CART';

// Cart
export const ADD_BURGER_TO_CART = 'ADD_BURGER_TO_CART';
export const REMOVE_BURGER_FROM_CART = 'REMOVE_BURGER_FROM_CART';

export const CLEAR_CART = 'CLEAR_CART';

export const REMOVE_ALL_ITEMS_BURGER_FROM_CART =
	'REMOVE_ALL_ITEMS_BURGER_FROM_CART';

// Ingredients

export const GET_ALL_INGREDIENTS = 'GET_ALL_INGREDIENTS';

// Custom Burger

export const INIT_CUSTOM_BURGER_INGREDIENTS = 'INIT_CUSTOM_BURGER_INGREDIENTS';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';

// Geo Location
export const UPDATE_LOCATION_COORDINATES = 'UPDATE_LOCATION_COORDINATES';
export const UPDATE_LOCATION_ERROR = 'UPDATE_LOCATION_ERROR';
export const UPDATE_BROWSER_ALLOW_LOCATION = 'UPDATE_BROWSER_ALLOW_LOCATION';
export const UPDATE_ALLOW_LOCATION = 'UPDATE_ALLOW_LOCATION';
