// Auth
export const CHECK_AUTH_USER_INIT = "CHECK_AUTH_USER_INIT";
export const CHECK_AUTH_USER_SUCCESS = "CHECK_AUTH_USER_SUCCESS";
export const CHECK_AUTH_USER_FAILED = "CHECK_AUTH_USER_FAILED";

export const REGISTER_USER_INIT = "REGISTER_USER_INIT";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const RESET_REGISTER_USER_STATUS = "RESET_REGISTER_USER_STATUS";

export const LOGIN_USER_INIT = "LOGIN_USER_INIT";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER_INIT = "LOGOUT_USER_INIT";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

export const SEND_EMAIL_CONFIRMATION_INIT = "SEND_EMAIL_CONFIRMATION_INIT";
export const SEND_EMAIL_CONFIRMATION_SUCCESS =
	"SEND_EMAIL_CONFIRMATION_SUCCESS";
export const SEND_EMAIL_CONFIRMATION_FAILED = "SEND_EMAIL_CONFIRMATION_FAILED";

export const VERIFY_ACCOUNT_INIT = "VERIFY_ACCOUNT_INIT";
export const VERIFY_ACCOUNT_SUCCESS = "VERIFY_ACCOUNT_SUCCESS";
export const VERIFY_ACCOUNT_FAILED = "VERIFY_ACCOUNT_FAILED";

// Menu

export const GET_BURGERS_INIT = "GET_BURGERS_INIT";
export const GET_BURGERS_SUCCESS = "GET_BURGERS_SUCCESS";
export const GET_BURGERS_FAILED = "GET_BURGERS_FAILED";

export const GET_NEW_BURGERS_INIT = "GET_NEW_BURGERS_INIT";
export const GET_NEW_BURGERS_SUCCESS = "GET_NEW_BURGERS_SUCCESS";
export const GET_NEW_BURGERS_FAILED = "GET_NEW_BURGERS_FAILED";

export const UPDATE_BURGER_ITEMS_IN_CART = "UPDATE_BURGER_ITEMS_IN_CART";

// Cart
export const ADD_BURGER_TO_CART = "ADD_BURGER_TO_CART";
export const REMOVE_BURGER_FROM_CART = "REMOVE_BURGER_FROM_CART";

export const CLEAR_CART = "CLEAR_CART";

export const REMOVE_ALL_ITEMS_BURGER_FROM_CART =
	"REMOVE_ALL_ITEMS_BURGER_FROM_CART";

// Ingredients

export const GET_ALL_INGREDIENTS_INIT = "GET_ALL_INGREDIENTS_INIT";
export const GET_ALL_INGREDIENTS_SUCCESS = "GET_ALL_INGREDIENTS_SUCCESS";
export const GET_ALL_INGREDIENTS_FAILED = "GET_ALL_INGREDIENTS_FAILED";

// Custom Burger

export const INIT_CUSTOM_BURGER_INGREDIENTS = "INIT_CUSTOM_BURGER_INGREDIENTS";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";

// Orders
export const PLACE_ORDER_INIT = "PLACE_ORDER_INIT";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";

export const RESET_ORDER_STATUS = "RESET_ORDER_STATUS";

// User

export const UPDATE_USER_DATA_INIT = "UPDATE_USER_DATA_INIT";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILED = "UPDATE_USER_DATA_FAILED";

export const GET_USER_ORDERS_INIT = "GET_USER_ORDERS_INIT";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAILED = "GET_USER_ORDERS_FAILED";

export const GET_USER_ORDER_INIT = "GET_USER_ORDER_INIT";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAILED = "GET_USER_ORDER_FAILED";

export const UPDATE_USER_ORDER_INIT = "UPDATE_USER_ORDER_INIT";
export const UPDATE_USER_ORDER_SUCCESS = "UPDATE_USER_ORDER_SUCCESS";
export const UPDATE_USER_ORDER_FAILED = "UPDATE_USER_ORDER_FAILED";

// Admin

export const GET_ALL_ORDERS_ADMIN_INIT = "GET_ALL_ORDERS_ADMIN_INIT";
export const GET_ALL_ORDERS_ADMIN_SUCCESS = "GET_ALL_ORDERS_ADMIN_SUCCESS";
export const GET_ALL_ORDERS_ADMIN_FAILED = "GET_ALL_ORDERS_ADMIN_FAILED";

export const GET_ALL_ORDERS_ADMIN_STATS_INIT =
	"GET_ALL_ORDERS_ADMIN_STATS_INIT";
export const GET_ALL_ORDERS_ADMIN_STATS_SUCCESS =
	"GET_ALL_ORDERS_ADMIN_STATS_SUCCESS";
export const GET_ALL_ORDERS_ADMIN_STATS_FAILED =
	"GET_ALL_ORDERS_ADMIN_STATS_FAILED";

export const GET_ALL_USERS_INIT = "GET_ALL_USERS_INIT";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";

export const DELETE_USER_INIT = "DELETE_USER_INIT";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
